; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html
[wifi_creditials]
build_flags =   '-DWIFI_SSID= "mySSID"'
                '-DWIFI_PASSWORD= "mySecretWifiPassword"'

[env:Tuya_2Button_Scene_Switch_083A8D429D14]
extends  = esp32c2_2M316
;upload_port = /dev/cu.usbserial-0001
upload_protocol = espota
upload_port = 192.168.1.100
upload_flags =  --auth=1234567890ABCDEF
build_flags = ${esp32c2_2M316.build_flags} 
        ${wifi_creditials.build_flags}
        -D ESP32C2WROOM06
        -D TUYA_2BUTTON_SCENE_SWITCH 
       '-DAUTHENTIFICATION_KEY= "1234567890ABCDEF"' 

[env:WizMote_XXXXXXXXXXXX]
extends  = esp8266_2M256
;upload_port = /dev/cu.usbserial-0001
upload_protocol = espota
upload_port = 192.168.1.101
upload_flags =  --auth=1234567890ABCDEF
build_flags = ${esp8266_2M256.build_flags} 
        ${wifi_creditials.build_flags}
        -D ESP_WROOM_02
        -D WIZMOTE_HC165 
        -D WIZMOTE_ACTIVE_LED_MOD
       '-DAUTHENTIFICATION_KEY= "1234567890ABCDEF"' 
       '-DCUSTOM_MAC_ADDRESS= "44:4F:8E:00:01:02"'

[env:WIFI4BUTTONREMOTE_XXXXXXXXXXXX]
extends  = esp8266_4M1M
;board = d1_mini
;upload_port = /dev/cu.usbserial-0001
upload_protocol = espota
upload_port = 192.168.1.102
upload_flags = --auth=1234567890ABCDEF
build_flags = ${esp8266_4M1M.build_flags} 
        ${wifi_creditials.build_flags}
        -D ESP12
        -D WIFI_4BUTTON_REMOTE_ON_1_2_OFF 
        -D AUTH_TOKEN_REQ=1
        '-DAUTHENTIFICATION_KEY= "1234567890ABCDEF"'

[env:Wemos_RESET_BUTTON_A4CF12DE7B75]
extends  = esp8266_4M1M
;upload_port = /dev/cu.usbserial-0001
upload_protocol = espota
upload_port = 192.168.1.103
upload_flags =  --auth=1234567890ABCDEF
build_flags = ${esp8266_4M1M.build_flags} 
        ${wifi_creditials.build_flags}
        -D ESP12
        -D BUTTON_RESET=1
        -D SETUP_PIN=14
       '-DAUTHENTIFICATION_KEY= "1234567890ABCDEF"' 