; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html
[wifi_creditials]
build_flags =   '-DWIFI_SSID= "mySSID"'
                '-DWIFI_PASSWORD= "mySecretWifiPassword"'

[env:Tuya_2Button_Scene_Switch_083A8D429D14]
extends  = esp32c2_2M316
;upload_port = /dev/cu.usbserial-0001
upload_protocol = espota
upload_port = 192.168.1.100
upload_flags =  --auth=1234567890ABCDEF
;monitor_port = /dev/cu.usbserial-0001
;monitor_filters = esp8266_exception_decoder
build_flags = ${esp32c2_2M316.build_flags} 
        ${wifi_creditials.build_flags}
        -D ESP32C2WROOM06
        -D TUYA_2BUTTON_SCENE_SWITCH 
       '-DAUTHENTIFICATION_KEY= "1234567890ABCDEF"' 

[env:WizMote_XXXXXXXXXXXX]
extends  = esp8266_2M256
;upload_port = /dev/cu.usbserial-0001
upload_protocol = espota
upload_port = 192.168.51.101
upload_flags =  --auth=1234567890ABCDEF
monitor_port = /dev/cu.usbserial-0001
monitor_filters = esp8266_exception_decoder
build_flags = ${esp8266_2M256.build_flags} 
        ${wifi_creditials.build_flags}
        -D ESP_WROOM_02
        -D WIZMOTE_HC165 
        -D WIZMOTE_ACTIVE_LED_MOD
       '-DAUTHENTIFICATION_KEY= "1234567890ABCDEF"' 
       '-DCUSTOM_MAC_ADDRESS= "44:4F:8E:00:01:02"'